#!/bin/sh /etc/rc.common

START=99

PROCESS=/mnt/sda1/frp/frpc
CONF=/mnt/sda1/frp/frpc_min.ini
LOG=/mnt/sda1/frp/frpc.log

start() {
    SERVICE_DAEMONIZE=1 \
        service_start $PROCESS -c $CONF >> $LOG
    return 0
}

stop() {
    if [ -n "`pidof frpc`" ]; then
        service_stop $PROCESS
    fi
    return 0
}

restart () {
    stop
    sleep 2
    start
}